version: "3.8"

services:
  customer:
    build: ./Client
    volumes:
      - ./Client:/Client
      - Client_node_modules:/Client/node_modules
    ports:
      - "2332:1234"
    depends_on:
      - mysql
      - kafka
      
  marketer:
    build: ./marketer
    volumes:
      - ./marketer:/marketer
      - marketer_node_modules:/marketer/node_modules
    ports:
      - "4321:4321"
    depends_on:
      - mysql
      - kafka
      - customer

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami/data
    environment:
      - "zookeeper_data:/bitnami"
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/data
    hostname: 'kafka-internal.io'
    environment:
      - "KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092"
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  mysql:
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=mydb"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    depends_on:
      - mysql

    environment:
      - "PMA_HOST=mysql"
      - "MYSQL_ROOT_PASSWORD=password"

volumes:
  zookeeper_data:
  kafka_data:
  mysql_data:
  Client_node_modules:
  marketer_node_modules:
